import { Category, Product, Order, ChatbotKnowledge } from '../types/index.js';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'low-carb',
    name: 'Low-Carb & KETO',
    slug: 'low-carb',
    description: 'Thực phẩm siêu ít tinh bột, giàu chất xơ hòa tan từ củ nưa Konjac & hạt hạnh nhân hữu cơ.',
    dietType: 'low-carb',
    icon: 'WheatOff',
    count: 3,
  },
  {
    id: 'high-protein',
    name: 'High-Protein (Giàu đạm)',
    slug: 'high-protein',
    description: 'Ức gà nấu chậm sous-vide, thanh hạt protein nạp đạm tinh khiết cho người tập gym và siết cơ.',
    dietType: 'high-protein',
    icon: 'Dumbbell',
    count: 3,
  },
  {
    id: 'sugar-free',
    name: 'Sugar-Free (0g Đường)',
    slug: 'sugar-free',
    description: 'Không đường mía tinh luyện, vị ngọt thanh tự nhiên từ cỏ ngọt Stevia và quả la hán.',
    dietType: 'sugar-free',
    icon: 'CandyOff',
    count: 3,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    code: 'NM-LC01',
    name: 'Bánh Mì Nguyên Cám Keto Hạnh Nhân',
    category: 'low-carb',
    categoryName: 'Low-Carb & Keto',
    price: 68000,
    originalPrice: 85000,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    description: 'Bánh mì làm từ bột hạnh nhân hữu cơ và hạt lanh, tinh chất xơ thực vật. Siêu ít tinh bột, thơm bùi tự nhiên, thích hợp cho bữa sáng Eat Clean & Keto.',
    ingredients: ['Bột hạnh nhân nguyên chất', 'Hạt lanh vàng', 'Bột vỏ mã đề (psyllium husk)', 'Lòng trắng trứng', 'Muối hồng Himalaya'],
    nutrition: {
      servingSize: '1 lát (50g)',
      calories: 95,
      protein: 7.2,
      carbs: 2.8,
      fat: 6.5,
      sugar: 0.5,
      fiber: 4.8,
      sodium: 120,
    },
    stock: 45,
    rating: 4.9,
    reviewCount: 128,
    badges: ['Low-Carb', 'Keto Friendly', 'Giàu chất xơ'],
    isFeatured: true,
    bestFor: 'Người ăn kiêng Low-Carb, Das, KETO và kiểm soát đường huyết',
  },
  {
    id: 'prod-2',
    code: 'NM-HP01',
    name: 'Ức Gà Nấu Chậm Sous-Vide Sốt Tiêu Đen',
    category: 'high-protein',
    categoryName: 'Giàu Đạm (High-Protein)',
    price: 49000,
    originalPrice: 60000,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
    description: 'Ức gà phi lê tươi ngon 100% không da, nấu chậm công nghệ sous-vide giữ trọn độ mọng nước mềm thơm. Chứa tới 31g đạm tinh khiết, 0 đường bổ sung.',
    ingredients: ['Ức gà ta nuôi tự nhiên 95%', 'Tiêu đen Phú Quốc đập dập', 'Muối khoáng', 'Dầu ô liu extra virgin', 'Hương thảo tươi'],
    nutrition: {
      servingSize: '1 gói (150g)',
      calories: 165,
      protein: 31.5,
      carbs: 1.2,
      fat: 2.8,
      sugar: 0.1,
      sodium: 290,
    },
    stock: 80,
    rating: 4.95,
    reviewCount: 240,
    badges: ['High-Protein', 'Đạm 31g', '0g Đường'],
    isFeatured: true,
    bestFor: 'Người tập gym, tăng cơ giảm mỡ, thể hình và vận động viên',
  },
  {
    id: 'prod-3',
    code: 'NM-SF01',
    name: 'Trà Kombucha Men Sống 0 Sugar Táo Quế',
    category: 'sugar-free',
    categoryName: 'Không Đường (Sugar-Free)',
    price: 35000,
    originalPrice: 42000,
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80',
    description: 'Trà lên men tự nhiên Scoby cao cấp kết hợp chiết xuất táo xanh và quế tự nhiên. Lên men hoàn toàn 21 ngày, không thêm đường mía, giàu probiotic đường ruột.',
    ingredients: ['Trà xanh hữu cơ Shan Tuyết', 'Con giống nấm Scoby', 'Chiết xuất táo xanh tự nhiên', 'Vỏ quế Yên Bái', 'Lợi khuẩn Bacillus Coagulans'],
    nutrition: {
      servingSize: '1 chai (250ml)',
      calories: 18,
      protein: 0.2,
      carbs: 3.5,
      fat: 0.0,
      sugar: 0.0,
      sodium: 15,
    },
    stock: 120,
    rating: 4.8,
    reviewCount: 95,
    badges: ['Sugar-Free', 'Men vi sinh Probiotic', '0g Đường'],
    isFeatured: true,
    bestFor: 'Hỗ trợ tiêu hóa, thanh lọc cơ thể, người kiêng đường và giảm cân',
  },
  {
    id: 'prod-4',
    code: 'NM-LC02',
    name: 'Bún Nưa Shirataki Tươi Konjac 0 Calo',
    category: 'low-carb',
    categoryName: 'Low-Carb & Keto',
    price: 28000,
    originalPrice: 35000,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    description: 'Bún sợi từ củ nưa Konjac Nhật Bản, chỉ 9 kcal mỗi 100g, chứa chất xơ Glucomannan tạo cảm giác no lâu, thay thế hoàn hảo cho bún gạo và mì truyền thống.',
    ingredients: ['Bột nưa Konjac tinh khiết 97%', 'Nước tinh khiết', 'Canxi hydroxit (chất tạo đông tự nhiên)'],
    nutrition: {
      servingSize: '1 túi (200g)',
      calories: 18,
      protein: 0.4,
      carbs: 1.0,
      fat: 0.1,
      sugar: 0.0,
      fiber: 5.2,
      sodium: 20,
    },
    stock: 95,
    rating: 4.75,
    reviewCount: 164,
    badges: ['0 Calo Concept', 'Low-Carb', 'Giàu chất xơ'],
    isFeatured: false,
    bestFor: 'Người cần giảm mỡ cấp tốc, hạn chế tối đa calo và tinh bột',
  },
  {
    id: 'prod-5',
    code: 'NM-HP02',
    name: 'Thanh Hạt Protein Bar Đậu Phộng & Hạt Chia',
    category: 'high-protein',
    categoryName: 'Giàu Đạm (High-Protein)',
    price: 32000,
    originalPrice: 39000,
    image: 'https://images.unsplash.com/photo-1622484216802-005085603a11?auto=format&fit=crop&w=600&q=80',
    description: 'Thanh năng lượng giàu đạm từ whey isolate thực vật, hạt óc chó, hạnh nhân và bơ đậu phộng nguyên chất. Tiện lợi nạp trước hoặc sau buổi tập thể thao.',
    ingredients: ['Whey Protein Isolate thực vật', 'Bơ đậu phộng rang mộc', 'Hạt chia đen', 'Hạnh nhân lát', 'Bột ca cao nguyên chất', 'Mật hoa dừa'],
    nutrition: {
      servingSize: '1 thanh (50g)',
      calories: 185,
      protein: 16.5,
      carbs: 8.2,
      fat: 7.8,
      sugar: 1.8,
      fiber: 4.5,
      sodium: 85,
    },
    stock: 150,
    rating: 4.9,
    reviewCount: 310,
    badges: ['High-Protein', '16.5g Protein', 'Bữa phụ tiện lợi'],
    isFeatured: true,
    bestFor: 'Bữa phụ năng lượng lành mạnh, nạp đạm cho gymer và dân văn phòng',
  },
  {
    id: 'prod-6',
    code: 'NM-SF02',
    name: 'Sô Cô La Đen 85% Cacao Thuần Chay Stevia',
    category: 'sugar-free',
    categoryName: 'Không Đường (Sugar-Free)',
    price: 65000,
    originalPrice: 78000,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=600&q=80',
    description: 'Thanh chocolate đen Bến Tre thượng hạng, 85% cacao nguyên bản phối lá cỏ ngọt tự nhiên Stevia. Vị đắng sâu thanh tao, không làm tăng vọt chỉ số đường huyết GI.',
    ingredients: ['Hạt cacao Bến Tre lên men', 'Bơ cacao tự nhiên', 'Bột lá cỏ ngọt Stevia organic', 'Hạt vani tự nhiên'],
    nutrition: {
      servingSize: '1 phần (30g)',
      calories: 145,
      protein: 3.2,
      carbs: 5.8,
      fat: 12.0,
      sugar: 0.2,
      fiber: 4.0,
      sodium: 5,
    },
    stock: 60,
    rating: 4.88,
    reviewCount: 89,
    badges: ['Sugar-Free', '85% Cacao', 'Giàu chất chống oxy hóa'],
    isFeatured: false,
    bestFor: 'Người thèm ngọt nhưng kiêng đường, bệnh nhân tiểu đường, người ăn keto',
  },
  {
    id: 'prod-7',
    code: 'NM-HP03',
    name: 'Bơ Đậu Phộng Mộc 100% Không Đường',
    category: 'high-protein',
    categoryName: 'Giàu Đạm (High-Protein)',
    price: 75000,
    originalPrice: 90000,
    image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?auto=format&fit=crop&w=600&q=80',
    description: 'Chỉ gồm 100% đậu phộng hạt loại 1 rang chín vàng xay mịn nhuyễn. Hoàn toàn không dầu cọ hydro hóa, không đường, không muối, giàu chất béo tốt và đạm thực vật.',
    ingredients: ['100% Đậu phộng Đắk Lắk chọn lọc rang chín thơm'],
    nutrition: {
      servingSize: '2 thìa (32g)',
      calories: 190,
      protein: 8.5,
      carbs: 6.0,
      fat: 16.0,
      sugar: 1.2,
      fiber: 2.5,
      sodium: 10,
    },
    stock: 75,
    rating: 4.92,
    reviewCount: 145,
    badges: ['100% Tự nhiên', 'High-Protein', 'Không dầu cọ'],
    isFeatured: false,
    bestFor: 'Ăn kèm bánh mì nguyên cám, sinh tố protein, người cần bổ sung calo sạch',
  },
  {
    id: 'prod-8',
    code: 'NM-LC03',
    name: 'Granola Nướng Mộc Hạt Hạnh Nhân & Macca (Keto)',
    category: 'low-carb',
    categoryName: 'Low-Carb & Keto',
    price: 119000,
    originalPrice: 145000,
    image: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=600&q=80',
    description: 'Granola thế hệ mới 0% yến mạch, 100% từ 6 loại hạt dinh dưỡng thượng hạng (Macca, Hạt điều, Hạnh nhân, Bí xanh, Hướng dương, Hạt chia). Vị giòn rụm với bơ ghee.',
    ingredients: ['Hạt mắc ca Tây Nguyên', 'Hạnh nhân Mỹ', 'Hạt óc chó Chile', 'Hạt bí xanh', 'Hạt hướng dương', 'Bơ Ghee', 'Quế'],
    nutrition: {
      servingSize: '1 khẩu phần (45g)',
      calories: 220,
      protein: 6.8,
      carbs: 4.5,
      fat: 18.5,
      sugar: 1.1,
      fiber: 4.2,
      sodium: 45,
    },
    stock: 55,
    rating: 4.96,
    reviewCount: 202,
    badges: ['0% Yến mạch', 'Low-Carb', 'Keto Siêu Hạt'],
    isFeatured: true,
    bestFor: 'Bữa sáng nhanh, ăn kèm sữa chua Hy Lạp không đường',
  },
  {
    id: 'prod-9',
    code: 'NM-SF03',
    name: 'Mứt Dâu Rừng Chia Hữu Cơ Không Đường',
    category: 'sugar-free',
    categoryName: 'Không Đường (Sugar-Free)',
    price: 58000,
    originalPrice: 70000,
    image: 'https://images.unsplash.com/photo-1577906096429-f73c2c312435?auto=format&fit=crop&w=600&q=80',
    description: 'Mứt dâu Đà Lạt nấu chậm cùng hạt chia đen tạo độ sệt tự nhiên không cần gelatin hay pectin nhân tạo. Vị chua ngọt tự nhiên từ quả mọng, 0% đường tinh luyện.',
    ingredients: ['Dâu tây tươi Đà Lạt 80%', 'Hạt chia organic 12%', 'Nước cốt chanh tươi', 'Chiết xuất quả la hán'],
    nutrition: {
      servingSize: '1 thìa (20g)',
      calories: 22,
      protein: 0.6,
      carbs: 4.2,
      fat: 0.5,
      sugar: 1.5,
      fiber: 2.0,
      sodium: 5,
    },
    stock: 68,
    rating: 4.82,
    reviewCount: 76,
    badges: ['Sugar-Free', 'Quả mọng tự nhiên', 'Giàu Vitamin C'],
    isFeatured: false,
    bestFor: 'Phết bánh mì keto, pancake yến mạch hoặc pha trà hoa quả mát lạnh',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderCode: 'NM-849201',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    customer: {
      name: 'Nguyễn Văn Hùng',
      phone: '0912345678',
      email: 'hung.nguyen@example.com',
      address: '123 Đường 3/2, Phường Xuân Khánh, Quận Ninh Kiều, Cần Thơ',
    },
    items: [
      {
        productId: 'prod-2',
        productName: 'Ức Gà Nấu Chậm Sous-Vide Sốt Tiêu Đen',
        productImage: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
        price: 49000,
        quantity: 3,
        calories: 165,
        protein: 31.5,
      },
      {
        productId: 'prod-4',
        productName: 'Bún Nưa Shirataki Tươi Konjac 0 Calo',
        productImage: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
        price: 28000,
        quantity: 4,
        calories: 18,
        protein: 0.4,
      },
    ],
    totalAmount: 259000,
    totalCalories: 567,
    totalProtein: 96.1,
    shippingFee: 20000,
    paymentMethod: 'vietqr',
    paymentStatus: 'paid',
    status: 'delivered',
    notes: 'Giao giờ hành chính giúp em ạ.',
  },
];

export const INITIAL_CHAT_KNOWLEDGE: ChatbotKnowledge[] = [
  {
    id: 1,
    intentTag: 'low_carb_keto',
    keywordPatterns: ['keto', 'low-carb', 'low carb', 'ít tinh bột', 'giảm cân', 'bụng mỡ', 'tinh bột'],
    answerTemplate: 'Chế độ Low-Carb / Keto tập trung cắt giảm carbohydrate tinh chế (dưới 20-50g carbs thuần/ngày) để cơ thể chuyển sang trạng thái đốt mỡ tự nhiên. NutriMate có các sản phẩm tiêu biểu như Bún Nưa Shirataki 0 Calo, Bánh Mì Nguyên Cám Hạnh Nhân và Granola Hạt Siêu Bùi.',
    recommendedCategory: 'low-carb',
  },
  {
    id: 2,
    intentTag: 'high_protein_gym',
    keywordPatterns: ['protein', 'đạm', 'gym', 'tập tạ', 'tăng cơ', 'siết cơ', 'thể hình', 'cơ bắp'],
    answerTemplate: 'Để phát triển và phục hồi cơ bắp tối ưu, bạn cần nạp khoảng 1.6g - 2.2g protein trên mỗi kg thể trọng mỗi ngày. Danh mục High-Protein của NutriMate cung cấp ức gà nấu chậm sous-vide mềm ngọt (31.5g đạm), thanh protein bar hạt chia và bơ đậu phộng mộc 100%.',
    recommendedCategory: 'high-protein',
  },
  {
    id: 3,
    intentTag: 'sugar_free_diabetes',
    keywordPatterns: ['đường', 'tiểu đường', 'sugar', 'huyết áp', 'kiêng ngọt', 'không đường', 'thèm ngọt'],
    answerTemplate: 'Cắt giảm đường tinh luyện giúp ổn định đường huyết, giảm mỡ nội tạng và làm chậm lão hóa. Bạn hoàn toàn có thể thưởng thức vị ngọt lành mạnh nhờ trà Kombucha men sống 0 sugar, sô-cô-la đen 85% cacao cỏ ngọt Stevia và mứt dâu rừng hạt chia.',
    recommendedCategory: 'sugar-free',
  },
];
